#services:
#  db:
#    image: mysql:8
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: ecomdb
#    ports:
#      - "3307:3306"
#    networks:
#      - ecom-network
#
#  app:
#    build: .
#    container_name: springboot-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    networks:
#      - ecom-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecomdb
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#
#networks:
#  ecom-network:
#    driver: bridge


services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ecomdbb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - ecom-network
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8085"
    depends_on:
      - db
    networks:
      - ecom-network
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ecom-network
networks:
  ecom-network:
    driver: bridge
